apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-commerce-app
  template:
    metadata:
      labels:
        app: e-commerce-app
    spec:
      containers:
      - name: e-commerce-app
        image: e-commerce-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: e-commerce-app-service
spec:
  type: NodePort
  selector:
    app: e-commerce-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
